### ISSUE TITLE
Cannot query field "stepsOnBranch" on type WorkflowOnBranch

### ISSUE THREAD

**Issue by jasonLaster** [replayio-public/qa-wolf#1]
```
Querying API workflowsListPage qawolf_1788eef008ff4d0dbea23904cc245614
{"errors":[{"message":"Cannot query field \"stepsOnBranch\" on type \"WorkflowOnBranch\".","locations":[{"line":27,"column":5}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}

/Users/jasonlaster/src/replay/qa-wolf/sync.ts:125
    return JSON.parse(body).data.workflowOnBranches.map(
                                ^
TypeError: Cannot read properties of undefined (reading 'workflowOnBranches')
    at queryTests (/Users/jasonlaster/src/replay/qa-wolf/sync.ts:125:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/Users/jasonlaster/src/replay/qa-wolf/sync.ts:150:17)
    at async main (/Users/jasonlaster/src/replay/qa-wolf/run.ts:17:3)
    ```

**Comment by jasonLaster** [comment]
Confirmed this is also what's failing in buildkite

```
-- Syncing Tests --
{"errors":[{"message":"Cannot query field \"stepsOnBranch\" on type \"WorkflowOnBranch\".","locations":[{"line":27,"column":9}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}]}
 
/opt/homebrew/var/buildkite-agent/builds/macos-chromium-test-runner-1/replay/runtime-qa-wolf-tests/test/runtime/qa_wolf/sync.ts:130
    return JSON.parse(body).data.workflowOnBranches.map((workflowOnBranch: any) => {
                                ^
TypeError: Cannot read properties of undefined (reading 'workflowOnBranches')
    at queryTests (/opt/homebrew/var/buildkite-agent/builds/macos-chromium-test-runner-1/replay/runtime-qa-wolf-tests/test/runtime/qa_wolf/sync.ts:130:33)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (/opt/homebrew/var/buildkite-agent/builds/macos-chromium-test-runner-1/replay/runtime-qa-wolf-tests/test/runtime/qa_wolf/sync.ts:153:17)
    at async main (/opt/homebrew/var/buildkite-agent/builds/macos-chromium-test-runner-1/replay/runtime-qa-wolf-tests/test/runtime/qa_wolf/run.ts:83:3)
Command /opt/homebrew/var/buildkite-agent/builds/macos-chromium-test-runner-1/replay/runtime-qa-wolf-tests/test/runtime/qa_wolf/node_modules/.bin/ts-node --project /opt/homebrew/var/buildkite-agent/builds/macos-chromium-test-runner-1/replay/runtime-qa-wolf-tests/test/runtime/qa_wolf/tsconfig.json run.ts failed with status 1
/opt/homebrew/var/buildkite-agent/builds/macos-chromium-test-runner-1/replay/runtime-qa-wolf-tests/test/runtime/qa_wolf/buildkite.js:25
    throw new Error(`Command ${command} failed with status ${result.status}`);
    ^
 
Error: Command /opt/homebrew/var/buildkite-agent/builds/macos-chromium-test-runner-1/replay/runtime-qa-wolf-tests/test/runtime/qa_wolf/node_modules/.bin/ts-node --project /opt/homebrew/var/buildkite-agent/builds/macos-chromium-test-runner-1/replay/runtime-qa-wolf-tests/test/runtime/qa_wolf/tsconfig.json run.ts failed with status 1
    at runCommand (/opt/homebrew/var/buildkite-agent/builds/macos-chromium-test-runner-1/replay/runtime-qa-wolf-tests/test/runtime/qa_wolf/buildkite.js:25:11)
    at Object.<anonymous> (/opt/homebrew/var/buildkite-agent/builds/macos-chromium-test-runner-1/replay/runtime-qa-wolf-tests/test/runtime/qa_wolf/buildkite.js:48:1)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:128:12)
    at node:internal/main/run_main_module:28:49
```

**Comment by jcmorrow** [comment]
Fixed in https://github.com/replayio-public/qa-wolf/commit/a7ffa1b9d171c31e48e81fb5f0edaaf776d78969
